"""
Embeds the Ahadu Bank logo image as a base64 data URI directly into
the AhaduLogo.tsx component. After running this, the logo is self-contained
and works on any machine without needing the image file.

Usage:
  1. Copy your logo image to: frontend/public/ahadu-logo.png
  2. Run: py embed_logo.py
"""
import base64
import os
import sys
from pathlib import Path

# Look for the logo in multiple locations
SEARCH_PATHS = [
    Path(r"A:\ML Model project\AHADU PULSE\frontend\public\ahadu-logo.png"),
    Path(r"A:\ML Model project\AHADU PULSE\frontend\public\ahadu-logo.jpg"),
    Path(r"A:\ML Model project\AHADU PULSE\frontend\public\ahadu-logo.jpeg"),
    Path(r"A:\ML Model project\AHADU PULSE\frontend\public\ahadu-logo.webp"),
    Path(r"A:\ML Model project\AHADU PULSE\frontend\public\logo.png"),
    Path(r"A:\ML Model project\AHADU PULSE\frontend\public\logo.jpg"),
]

img_path = None
for p in SEARCH_PATHS:
    if p.exists():
        img_path = p
        break

if not img_path:
    print("ERROR: Logo image not found.")
    print("Please copy your Ahadu Bank logo to:")
    print("  A:\\ML Model project\\AHADU PULSE\\frontend\\public\\ahadu-logo.png")
    sys.exit(1)

print(f"Found logo: {img_path} ({img_path.stat().st_size:,} bytes)")

# Read and encode
ext = img_path.suffix.lower().lstrip(".")
mime = {
    "png":  "image/png",
    "jpg":  "image/jpeg",
    "jpeg": "image/jpeg",
    "webp": "image/webp",
    "svg":  "image/svg+xml",
}.get(ext, "image/png")

data = base64.b64encode(img_path.read_bytes()).decode("utf-8")
data_uri = f"data:{mime};base64,{data}"
print(f"Encoded: {len(data_uri):,} chars (mime: {mime})")

# Write the component
COMPONENT = r"""/**
 * Ahadu Bank Official Logo — Embedded as base64 data URI.
 * Self-contained: works on any machine, no external file needed.
 * Generated by embed_logo.py — re-run if you update the logo image.
 */

interface AhaduLogoProps {
  size?: number;
  className?: string;
}

// Official Ahadu Bank logo embedded as base64 — portable across all environments
const LOGO_DATA_URI = "%%DATA_URI%%";

export default function AhaduLogo({
  size = 48,
  className = "",
}: AhaduLogoProps) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={LOGO_DATA_URI}
      alt="Ahadu Bank"
      width={size}
      height={size}
      style={{ objectFit: "contain", width: size, height: size }}
      className={className}
    />
  );
}
"""

component_content = COMPONENT.replace("%%DATA_URI%%", data_uri)

# For square logos with white background, use contain + slight rounding
component_content = component_content.replace(
    'objectFit: "cover"',
    'objectFit: "contain"'
)

out_path = Path(r"A:\ML Model project\AHADU PULSE\frontend\components\AhaduLogo.tsx")
out_path.write_text(component_content, encoding="utf-8")

print(f"\nSuccess! Logo embedded into: {out_path}")
print(f"Component size: {out_path.stat().st_size:,} bytes")
print("\nThe logo is now self-contained.")
print("It will work on any machine without needing the image file.")
print("\nRestart your Next.js dev server to see the change.")
